### INDEX
GET http://localhost:3000/

### GET YOKAI
GET http://localhost:3000/yokai


### GET YOKAI FOR ID
GET http://localhost:3000/yokai/1


### GET YOKAI FOR TRIBU
GET http://localhost:3000/yokai?tribu=Valiente

### GET YOKAI FOR RANGO

GET http://localhost:3000/yokai?rango=E


### POST YOKAI
POST http://localhost:3000/yokai
Content-Type: application/json

{
    "img": "https://mtwildwood.net/yokaiArt/icons/iconWashogun.png",
    "nombre": "HOLA",
    "tribu": "Valiente",
    "rango": "B",
    "elemento_debil": "Fuego",
    "foto": 1,
    "bando": "Ambos"
}


### PATCH YOKAI
PATCH http://localhost:3000/yokai/6
Content-Type: application/json

{
    "img": "https://mtwildwood.net/yokaiArt/icons/iconSlackaslash.png"
}

### DELETE YOKAI
DELETE http://localhost:3000/yokai/9