### INDEX
GET http://localhost:3000/

### GET YOKAI
GET http://localhost:3000/yokai


### GET YOKAI FOR ID
GET http://localhost:3000/yokai/1323ba0c-0aee-48b6-a1bd-ac42460502ad


### GET YOKAI FOR TRIBU
GET http://localhost:3000/yokai?tribu=Valiente

### GET YOKAI FOR RANGO

GET http://localhost:3000/yokai?rango=E


### POST YOKAI
POST http://localhost:3000/yokai
Content-Type: application/json

{
    "nombre": "Alcaldero",
    "tribu": "Misterioso",
    "rango": "E"
}


### PATCH YOKAI
PATCH http://localhost:3000/yokai/f7f2485d-3086-4cba-808a-169433506dd7
Content-Type: application/json

{
    "rango": "A"
}